import { expect, test } from '@playwright/test';

test('核心计划工作流和移动只读视图', async ({ page }) => {
  const username = `user_${Date.now()}`;
  await page.goto('/register');
  await page.getByLabel('用户名').fill(username);
  await page.getByLabel('密码', { exact: true }).fill('password123');
  await page.getByLabel('确认密码').fill('password123');
  await page.getByRole('button', { name: '创建账号' }).click();
  await expect(page.getByRole('heading', { name: '活跃计划' })).toBeVisible();

  await page.getByRole('button', { name: '新建领域' }).first().click();
  await page.getByLabel('领域名称').fill('工作');
  await page.getByRole('button', { name: '保存' }).click();
  await expect(page.getByRole('button', { name: /工作/ }).first()).toBeVisible();

  await page.getByRole('button', { name: '新建计划' }).first().click();
  await page.getByLabel('计划名称').fill('实习准备');
  await page.getByLabel('状态').selectOption('active');
  await page.getByLabel('说明').fill('准备学习、项目与投递路径');
  await page.getByRole('button', { name: '保存' }).click();
  await expect(page.getByRole('heading', { name: '活跃计划' })).toBeVisible();
  await expect(page.getByText('跨领域汇总 1 个进行中的计划')).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop-active-plans.png', fullPage: true });
  await page.getByRole('button', { name: /实习准备/ }).click();
  await expect(page.getByRole('heading', { name: '实习准备' })).toBeVisible();

  await expect(page.getByLabel('计划状态')).toHaveValue('active');
  await page.getByLabel('计划状态').selectOption('paused');
  await expect(page.getByText('计划状态已更新').last()).toBeVisible();
  await page.getByTitle('返回计划总览').click();
  await expect(page.getByText('跨领域汇总 0 个进行中的计划')).toBeVisible();
  await page.getByRole('button', { name: /全部计划/ }).click();
  await page.getByRole('button', { name: /实习准备/ }).click();
  await expect(page.getByRole('heading', { name: '实习准备' })).toBeVisible();
  await page.getByLabel('计划状态', { exact: true }).selectOption('active');
  await expect(page.getByText('计划状态已更新').last()).toBeVisible();
  await page.getByTitle('返回计划总览').click();
  await expect(page.getByText('跨领域汇总 1 个进行中的计划')).toBeVisible();
  await page.getByRole('button', { name: /实习准备/ }).click();
  await expect(page.getByRole('heading', { name: '实习准备' })).toBeVisible();
  await page.getByLabel('计划状态', { exact: true }).selectOption('planning');
  await expect(page.getByText('计划状态已更新').last()).toBeVisible();

  await page.getByRole('button', { name: 'AI 扩展' }).click();
  const graphAiModal = page.locator('.dialog-content').filter({ hasText: 'AI 扩展现有计划' });
  await expect(graphAiModal.getByLabel('目标计划')).toHaveValue(/.+/);
  await expect(graphAiModal.getByLabel('目标计划').locator('option:checked')).toHaveText(/实习准备/);
  await graphAiModal.getByRole('button', { name: '关闭' }).click();

  await page.getByRole('button', { name: '添加节点' }).click();
  await page.getByRole('button', { name: '添加节点' }).click();
  await expect(page.locator('.graph-node')).toHaveCount(2);
  await page.waitForTimeout(700);
  const source = page.locator('.graph-node').first().locator('.react-flow__handle.source');
  const target = page.locator('.graph-node').nth(1).locator('.react-flow__handle.target');
  const sourceBox = await source.boundingBox(); const targetBox = await target.boundingBox();
  if (!sourceBox || !targetBox) throw new Error('节点连接点不可见');
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(targetBox.x + targetBox.width / 2, targetBox.y + targetBox.height / 2, { steps: 20 });
  await page.waitForTimeout(150);
  await page.mouse.up();
  await expect(page.locator('.react-flow__edge')).toHaveCount(1);
  const selectedNodeCard = page.locator('.graph-node').first();
  await selectedNodeCard.click();
  await page.getByLabel('名称').fill('学习推理基础');
  const summaryInput = page.getByLabel('简短说明');
  await summaryInput.fill('完成基础知识梳理');
  await summaryInput.press('Home');
  await page.getByRole('button', { name: '插入当前日期' }).click();
  await expect(summaryInput).toHaveValue(/^\d{4}-\d{2}-\d{2}完成基础知识梳理$/);
  await page.getByRole('button', { name: '开始日期设为今天' }).click();
  await expect(page.getByLabel('节点状态')).toHaveValue('in_progress');
  await expect(selectedNodeCard).toHaveClass(/status-border-in_progress/);
  await expect(selectedNodeCard).toHaveCSS('border-top-color', 'rgb(59, 120, 191)');
  await expect(selectedNodeCard.locator('.node-status')).toHaveText('进行中');
  await expect(selectedNodeCard.locator('.node-status')).toHaveCSS('background-color', 'rgb(229, 240, 251)');
  await expect(page.getByText('计划已根据节点状态自动设为进行中').last()).toBeVisible();
  await expect(page.getByLabel('计划状态', { exact: true })).toHaveValue('active');
  const startDate = await page.getByLabel('开始日期').inputValue();
  const initialEndDate = await page.getByLabel('结束日期').inputValue();
  expect(startDate).toBeTruthy(); expect(initialEndDate).toBe('');
  await page.getByRole('button', { name: '+1天', exact: true }).click();
  const oneDayEndDate = await page.getByLabel('结束日期').inputValue();
  expect(oneDayEndDate).not.toBe(startDate);
  await page.getByRole('button', { name: '+1天', exact: true }).click();
  expect(await page.getByLabel('结束日期').inputValue()).not.toBe(oneDayEndDate);
  await expect(page.getByText('已保存')).toBeVisible();
  await page.getByRole('button', { name: '清除', exact: true }).click();
  await expect(page.getByLabel('开始日期')).toHaveValue('');
  await expect(page.getByLabel('结束日期')).toHaveValue('');
  await expect(page.getByLabel('节点状态')).toHaveValue('not_started');
  await expect(page.getByLabel('计划状态', { exact: true })).toHaveValue('active');
  await page.getByRole('button', { name: '开始日期设为今天' }).click();
  await expect(page.getByText('已保存')).toBeVisible();
  await page.getByRole('button', { name: '管理子阶段' }).click();
  const stepModal = page.locator('.dialog-content').filter({ hasText: '管理子阶段' });
  await stepModal.getByRole('button', { name: '添加子阶段' }).click();
  await stepModal.getByLabel('名称').fill('完成基础课程');
  await expect(stepModal.getByText('已保存')).toBeVisible();
  await stepModal.getByRole('button', { name: '添加子阶段' }).click();
  await stepModal.getByLabel('名称').fill('完成综合练习');
  const stepSummaryInput = stepModal.getByLabel('简短说明');
  await stepSummaryInput.fill('整理本阶段错题');
  await stepSummaryInput.press('End');
  await stepModal.getByRole('button', { name: '插入子阶段当前日期' }).click();
  await expect(stepSummaryInput).toHaveValue(/^整理本阶段错题\d{4}-\d{2}-\d{2}$/);
  await stepModal.getByRole('button', { name: '开始日期设为今天' }).click();
  await stepModal.getByRole('button', { name: '+一周', exact: true }).click();
  await expect(stepModal.getByLabel('开始日期')).not.toHaveValue('');
  await expect(stepModal.getByLabel('结束日期')).not.toHaveValue('');
  await expect(stepModal.getByText('已保存')).toBeVisible();
  await stepModal.getByTitle('上移').last().click();
  await expect(stepModal.getByText('已保存')).toBeVisible();
  await stepModal.screenshot({ path: 'test-results/desktop-node-steps.png' });
  await stepModal.getByRole('button', { name: '完成', exact: true }).click();
  await expect(page.locator('.graph-node').first().locator('.graph-node-steps')).toContainText('0/2');
  await expect(page.getByLabel('开始日期')).toBeDisabled();
  await page.getByRole('button', { name: '编辑附加信息' }).click();
  await page.locator('.cm-content').click();
  await page.keyboard.type('# 学习记录\n\n完成第一轮梳理。');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByText('附加信息已保存')).toBeVisible();
  await page.getByRole('button', { name: '关闭' }).first().click();
  await page.waitForTimeout(2800);
  await page.screenshot({ path: 'test-results/desktop-graph.png', fullPage: true });

  await page.getByTitle('返回计划总览').click();
  const activeCard = page.locator('.plan-card').filter({ hasText: '实习准备' });
  await expect(activeCard.getByText('当前活跃节点')).toBeVisible();
  await expect(activeCard.getByText('学习推理基础')).toBeVisible();
  await expect(activeCard.getByText('完成基础课程')).toBeVisible();
  await page.getByLabel('计划操作').click();
  await page.getByRole('menuitem', { name: '归档' }).click();
  await page.getByRole('button', { name: '确认归档' }).click();
  await page.getByRole('button', { name: /全部计划/ }).click();
  await expect(page.locator('.plan-card').filter({ hasText: '实习准备' }).locator('.archived-card-badge')).toHaveText('已归档');
  await page.screenshot({ path: 'test-results/desktop-all-plans.png', fullPage: true });
  await page.getByRole('button', { name: /已归档/ }).click();
  await expect(page.getByText('归档计划保持只读，可随时恢复或导出。')).toBeVisible();
  await page.getByRole('button', { name: '批量管理' }).click();
  await expect(page.getByLabel('选择计划 实习准备')).toBeVisible();
  await page.getByRole('button', { name: '选择全部' }).click();
  await expect(page.getByText('已选择 1 个计划')).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop-archived-batch.png', fullPage: true });
  await page.getByRole('button', { name: '退出批量' }).click();
  await page.getByRole('button', { name: /实习准备/ }).click();
  await expect(page.getByText('归档计划为只读状态。恢复后才能继续编辑。')).toBeVisible();
  await expect(page.getByRole('button', { name: '添加节点' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'AI 扩展' })).toHaveCount(0);
  await expect(page.getByLabel('计划状态')).toHaveCount(0);
  await page.getByTitle('返回计划总览').click();
  await page.getByLabel('计划操作').click();
  await page.getByRole('menuitem', { name: '恢复' }).click();
  await expect(page.getByText('计划已恢复')).toBeVisible();

  const areaRow = page.locator('.area-row').filter({ hasText: '工作' }).first();
  await areaRow.hover();
  await areaRow.getByLabel('工作领域操作').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('menuitem', { name: '导出领域' }).click();
  const areaDownload = await downloadPromise; const areaFilePath = await areaDownload.path();
  if (!areaFilePath) throw new Error('领域导出文件不可用');
  await page.getByRole('button', { name: '导入', exact: true }).click();
  await page.getByRole('menuitem', { name: '导入领域' }).click();
  await page.locator('input[type="file"]').setInputFiles(areaFilePath);
  await page.getByLabel('导入方式').selectOption('create');
  await expect(page.getByLabel('新领域名称')).toHaveValue('工作（导入）');
  await page.getByRole('button', { name: '导入领域', exact: true }).click();
  await expect(page.getByText(/领域“工作（导入）”已导入/)).toBeVisible();
  await expect(page.getByRole('button', { name: /工作（导入）/ }).first()).toBeVisible();
  await page.getByRole('button', { name: /活跃计划/ }).click();
  await expect(page.locator('.active-area-group')).toHaveCount(2);
  await page.screenshot({ path: 'test-results/desktop-active-plans-grouped.png', fullPage: true });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: /^工作 \d+$/ }).click();
  await expect(page.locator('.active-area-groups')).toHaveCount(0);
  await page.getByRole('button', { name: /实习准备/ }).click();
  await expect(page.getByText('移动端只读')).toBeVisible();
  await expect(page.getByRole('button', { name: '添加节点' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'AI 扩展' })).toHaveCount(0);
  await expect(page.getByLabel('计划状态')).toHaveCount(0);
  await expect(page.locator('.graph-node').first()).toBeVisible();
  await page.locator('.graph-node').first().click();
  await expect(page.getByRole('button', { name: '开始日期设为今天' })).toHaveCount(0);
  await page.getByRole('button', { name: '查看子阶段' }).click();
  await expect(page.getByRole('button', { name: '添加子阶段' })).toHaveCount(0);
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await page.waitForTimeout(2800);
  await page.screenshot({ path: 'test-results/mobile-graph.png', fullPage: true });
  await page.getByTitle('返回计划总览').click();
  await page.getByRole('button', { name: /活跃计划/ }).click();
  await expect(page.getByRole('heading', { name: '活跃计划' })).toBeVisible();
  await expect(page.getByText('跨领域汇总 2 个进行中的计划')).toBeVisible();
  const activeGroups = page.locator('.active-area-group');
  await expect(activeGroups).toHaveCount(2);
  await expect(activeGroups.nth(0).getByRole('heading', { name: '工作' })).toBeVisible();
  await expect(activeGroups.nth(1).getByRole('heading', { name: '工作（导入）' })).toBeVisible();
  await expect(activeGroups.nth(0).locator('.plan-card')).toHaveCount(1);
  await expect(activeGroups.nth(1).locator('.plan-card')).toHaveCount(1);
  await page.screenshot({ path: 'test-results/mobile-active-plans.png', fullPage: true });
});

test('AI 提示词、快照和增量 JSON 工作流', async ({ page }) => {
  const username = `ai_user_${Date.now()}`;
  await page.goto('/register');
  await page.getByLabel('用户名').fill(username);
  await page.getByLabel('密码', { exact: true }).fill('password123');
  await page.getByLabel('确认密码').fill('password123');
  await page.getByRole('button', { name: '创建账号' }).click();

  await page.getByRole('button', { name: '导入', exact: true }).click();
  await page.getByRole('menuitem', { name: 'AI 生成新计划' }).click();
  const snapshotPromptActions = page.locator('.ai-step').first().locator('.inline-actions');
  await expect(snapshotPromptActions.getByRole('button').nth(0)).toHaveText('构造提示词');
  await expect(snapshotPromptActions.getByRole('button').nth(1)).toHaveText('复制项目说明');
  await page.getByLabel('你的想法').fill('创建一个包含基础阶段和进阶阶段的训练计划');
  await page.getByText('高级选项').click();
  await page.getByLabel('建议领域').fill('AI 训练');
  await page.getByRole('button', { name: '构造提示词' }).click();
  await expect(page.getByLabel('生成的提示词')).toContainText('sixplan-plan-snapshot');
  const snapshot = {
    format: 'sixplan-plan-snapshot', version: 2, areaName: 'AI 训练',
    plan: { name: 'AI 长期训练', description: '由外部模型生成', status: 'active' },
    nodes: [{ key: 'base-stage', title: '基础阶段' }], edges: []
  };
  await page.getByLabel('粘贴 JSON').fill(JSON.stringify(snapshot));
  await page.getByRole('button', { name: '校验并预览' }).click();
  await expect(page.getByText('确认预览')).toBeVisible();
  await expect(page.getByText('最终节点')).toBeVisible();
  await expect(page.getByLabel('新领域名称')).toHaveValue('AI 训练');
  await page.locator('.preview-step').screenshot({ path: 'test-results/desktop-ai-snapshot-preview.png' });
  await page.getByRole('button', { name: '创建新计划' }).click();
  await expect(page.getByRole('button', { name: /AI 长期训练/ })).toBeVisible();

  await page.getByRole('button', { name: '导入', exact: true }).click();
  await page.getByRole('menuitem', { name: 'AI 扩展现有计划' }).click();
  const changesetPromptActions = page.locator('.ai-step').first().locator('.inline-actions');
  await expect(changesetPromptActions.getByRole('button').nth(0)).toHaveText('构造提示词');
  await expect(changesetPromptActions.getByRole('button').nth(1)).toHaveText('复制项目说明');
  await expect(page.getByLabel('目标计划')).toHaveValue(/.+/);
  await page.getByLabel('你的想法').fill('在基础阶段后增加进阶阶段');
  await page.getByText('上下文设置').click();
  const nodeCheckbox = page.getByLabel('选择节点 基础阶段');
  await expect(nodeCheckbox).toBeChecked(); await nodeCheckbox.uncheck();
  await expect(page.getByRole('button', { name: '构造提示词' })).toBeDisabled();
  await page.getByRole('button', { name: '仅选择叶节点' }).click(); await expect(nodeCheckbox).toBeChecked();
  await page.getByRole('button', { name: '选择全部' }).click(); await expect(nodeCheckbox).toBeChecked();
  await page.getByText('包含目标节点 Markdown', { exact: true }).click();
  await expect(page.getByLabel('包含目标节点 Markdown')).toBeChecked();
  await page.locator('.prompt-scope-picker').screenshot({ path: 'test-results/desktop-ai-scope-picker.png' });
  await page.getByRole('button', { name: '构造提示词' }).click();
  await expect(page.getByLabel('生成的提示词')).toContainText('sixplan-plan-changeset');
  await expect(page.getByLabel('生成的提示词')).toContainText('操作范围：所有节点（1/1）');
  await expect(page.getByLabel('生成的提示词')).toContainText('已提供目标节点现有 markdown');
  const changeset = {
    format: 'sixplan-plan-changeset', version: 2, targetPlanName: 'AI 长期训练', baseRevision: 1,
    operations: { addNodes: [{ key: 'advanced-stage', title: '进阶阶段' }], addEdges: [{ source: 'base-stage', target: 'advanced-stage' }] }
  };
  await page.getByLabel('粘贴 JSON').fill(JSON.stringify(changeset));
  await page.getByRole('button', { name: '校验并预览' }).click();
  await expect(page.getByText('确认预览')).toBeVisible();
  await expect(page.getByText('进阶阶段', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '应用增量变更' }).click();
  await expect(page.getByRole('heading', { name: 'AI 长期训练' })).toBeVisible();
  await expect(page.locator('.graph-node')).toHaveCount(2);
  await expect(page.locator('.react-flow__edge')).toHaveCount(1);
});
